#!/usr/bin/env node
/**
 * schedule.yaml -> launchd plists.
 *
 *   node deploy/gen.mjs            # render to deploy/launchd/, show a diff
 *   node deploy/gen.mjs --install  # also copy into ~/Library/LaunchAgents and load
 *
 * Generated files are committed so the diff is reviewable: a scheduling change
 * should show up in a PR like any other change.
 *
 * Dependency-free on purpose -- it runs with the system node (3.9-era macOS
 * python and a bare node are all we can assume), so the YAML subset used by
 * schedule.yaml is parsed here rather than pulling in a library.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "deploy", "launchd");
const INSTALL = process.argv.includes("--install");

const expand = (p) => p.replace(/^~/, homedir());

/** Minimal YAML reader for the shape schedule.yaml actually uses. */
function parseSchedule(text) {
  const defaults = {};
  const jobs = [];
  let inJobs = false;
  let cur = null;
  let cont = null; // key currently accumulating a `>` block

  for (const raw of text.split("\n")) {
    const line = raw.replace(/\t/g, "  ");
    if (!line.trim() || /^\s*#/.test(line)) continue;

    if (/^jobs:/.test(line)) { inJobs = true; continue; }
    if (/^defaults:/.test(line)) { inJobs = false; continue; }

    const indent = line.match(/^\s*/)[0].length;
    if (cont && indent > cont.indent) {
      cont.target[cont.key] += (cont.target[cont.key] ? " " : "") + line.trim();
      continue;
    }
    cont = null;

    const item = line.match(/^\s*-\s+(\w+):\s*(.*)$/);
    if (inJobs && item) {
      cur = {};
      jobs.push(cur);
      assign(cur, item[1], item[2], indent);
      continue;
    }
    const kv = line.match(/^\s*(\w+):\s*(.*)$/);
    if (!kv) continue;
    assign(inJobs ? cur : defaults, kv[1], kv[2], indent);
  }

  function assign(target, key, value, indent) {
    if (!target) return;
    if (value === ">" || value === "|") {
      target[key] = "";
      cont = { target, key, indent };
      return;
    }
    let v = value.replace(/\s+#.*$/, "").trim().replace(/^["']|["']$/g, "");
    if (v === "true") v = true;
    else if (v === "false") v = false;
    target[key] = v;
  }

  return { defaults, jobs };
}

/** "15m" / "6h" / "90s" -> seconds */
function toSeconds(every) {
  const m = String(every).match(/^(\d+)([smh])$/);
  if (!m) throw new Error(`bad interval: ${every}`);
  return Number(m[1]) * { s: 1, m: 60, h: 3600 }[m[2]];
}

const xml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function plist(job, defaults) {
  const label = `${defaults.label_prefix}.${job.name}`;
  const logDir = expand(defaults.log_dir || "~/Library/Logs");
  const args = ["/bin/bash", "-lc", `cd ${ROOT} && ${job.command}`];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- GENERATED by deploy/gen.mjs from config/schedule.yaml. Do not edit. -->
    <key>Label</key>
    <string>${label}</string>

    <key>ProgramArguments</key>
    <array>
${args.map((a) => `        <string>${xml(a)}</string>`).join("\n")}
    </array>

    <key>StartInterval</key>
    <integer>${toSeconds(job.every)}</integer>

    <key>RunAtLoad</key>
    <${defaults.run_at_load === true ? "true" : "false"}/>

    <!-- .out.log, not .log: a job whose wrapper already writes its own
         structured log would otherwise have two writers on one file. -->
    <key>StandardOutPath</key>
    <string>${logDir}/${job.name}.out.log</string>
    <key>StandardErrorPath</key>
    <string>${logDir}/${job.name}.err.log</string>

    <key>ProcessType</key>
    <string>Background</string>
    <key>LowPriorityIO</key>
    <true/>
</dict>
</plist>
`;
}

const { defaults, jobs } = parseSchedule(readFileSync(path.join(ROOT, "config/schedule.yaml"), "utf8"));
mkdirSync(OUT, { recursive: true });

const enabled = jobs.filter((j) => j.enabled !== false);
const skipped = jobs.filter((j) => j.enabled === false);

for (const job of enabled) {
  const file = path.join(OUT, `${defaults.label_prefix}.${job.name}.plist`);
  const next = plist(job, defaults);
  const prev = existsSync(file) ? readFileSync(file, "utf8") : null;
  writeFileSync(file, next);
  console.log(`${prev === next ? "  unchanged" : prev ? "  updated  " : "  created  "} ${path.basename(file)}  (every ${job.every})`);
}
for (const job of skipped) console.log(`  disabled  ${job.name}  — ${String(job.why || "").slice(0, 60)}`);

if (!INSTALL) {
  console.log(`\n${enabled.length} job(s) rendered to deploy/launchd/. Re-run with --install to load them.`);
  process.exit(0);
}

const AGENTS = path.join(homedir(), "Library/LaunchAgents");
for (const job of enabled) {
  const label = `${defaults.label_prefix}.${job.name}`;
  const src = path.join(OUT, `${label}.plist`);
  const dst = path.join(AGENTS, `${label}.plist`);
  writeFileSync(dst, readFileSync(src));
  const uid = process.getuid();
  try { execFileSync("launchctl", ["bootout", `gui/${uid}/${label}`], { stdio: "ignore" }); } catch {}
  execFileSync("launchctl", ["bootstrap", `gui/${uid}`, dst]);
  console.log(`  loaded    ${label}`);
}
