#!/usr/bin/env bun
/**
 * schedule.yaml -> launchd plists.
 *
 *   bun deploy/gen.mjs            # render to deploy/launchd/, show a diff
 *   bun deploy/gen.mjs --install  # also copy into ~/Library/LaunchAgents and load
 *
 * Generated files are committed so the diff is reviewable: a scheduling change
 * should show up in a PR like any other change.
 *
 * Schedule parsing lives in lib/schedule.mjs so this and the foreground
 * supervisor (orchestrator/run.mjs) always read the same jobs from the same
 * file -- two parsers is how the two execution modes would drift.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import path from "node:path";
import { loadSchedule, toSeconds, ROOT } from "../lib/schedule.mjs";
const OUT = path.join(ROOT, "deploy", "launchd");
const INSTALL = process.argv.includes("--install");

const expand = (p) => p.replace(/^~/, homedir());


const xml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function plist(job, defaults) {
  const label = `${defaults.label_prefix}.${job.name}`;
  const logDir = expand(defaults.log_dir || "~/Library/Logs");
  const args = ["/bin/bash", "-lc", `cd ${ROOT} && ${job.command}`];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- GENERATED by deploy/gen.mjs from config/schedule.yaml. Do not edit. -->
    <key>Label</key>
    <string>${label}</string>

    <key>ProgramArguments</key>
    <array>
${args.map((a) => `        <string>${xml(a)}</string>`).join("\n")}
    </array>

    <key>StartInterval</key>
    <integer>${toSeconds(job.every)}</integer>

    <key>RunAtLoad</key>
    <${defaults.run_at_load === true ? "true" : "false"}/>

    <!-- .out.log, not .log: a job whose wrapper already writes its own
         structured log would otherwise have two writers on one file. -->
    <key>StandardOutPath</key>
    <string>${logDir}/${job.name}.out.log</string>
    <key>StandardErrorPath</key>
    <string>${logDir}/${job.name}.err.log</string>

    <key>ProcessType</key>
    <string>Background</string>
    <key>LowPriorityIO</key>
    <true/>
</dict>
</plist>
`;
}

const { defaults, jobs } = loadSchedule();
mkdirSync(OUT, { recursive: true });

const enabled = jobs.filter((j) => j.enabled !== false);
const skipped = jobs.filter((j) => j.enabled === false);

for (const job of enabled) {
  const file = path.join(OUT, `${defaults.label_prefix}.${job.name}.plist`);
  const next = plist(job, defaults);
  const prev = existsSync(file) ? readFileSync(file, "utf8") : null;
  writeFileSync(file, next);
  console.log(`${prev === next ? "  unchanged" : prev ? "  updated  " : "  created  "} ${path.basename(file)}  (every ${job.every})`);
}
for (const job of skipped) console.log(`  disabled  ${job.name}  — ${String(job.why || "").slice(0, 60)}`);

if (!INSTALL) {
  console.log(`\n${enabled.length} job(s) rendered to deploy/launchd/. Re-run with --install to load them.`);
  process.exit(0);
}

const AGENTS = path.join(homedir(), "Library/LaunchAgents");
for (const job of enabled) {
  const label = `${defaults.label_prefix}.${job.name}`;
  const src = path.join(OUT, `${label}.plist`);
  const dst = path.join(AGENTS, `${label}.plist`);
  writeFileSync(dst, readFileSync(src));
  const uid = process.getuid();
  try { execFileSync("launchctl", ["bootout", `gui/${uid}/${label}`], { stdio: "ignore" }); } catch {}
  execFileSync("launchctl", ["bootstrap", `gui/${uid}`, dst]);
  console.log(`  loaded    ${label}`);
}
